language: android
dist: trusty
android:
  components:
    - build-tools-29.0.3
    - android-29

script:
  - chmod +x ./gradlew
  - ./gradlew clean :oauth:clean oauth:assembleRelease

deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew :oauth:bintrayUpload
  on:
    branch: master