language: android
dist: trusty

before_install:
  - chmod +x gradlew

android:
  components:
    - build-tools-29.0.3
    - android-29

script:
  - ./gradlew clean :oauth:clean oauth:assembleRelease

deploy:
  provider: script
  script: ./gradlew :cieloecommerceoauth:bintrayUpload
  on:
    branch: master